services:
  mysql:
    container_name: respawn_hub_mysql
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: PfSLhLCdnqlD9E66OvSl8etKiplO2AW
      MYSQL_DATABASE: respawn_hub_db
      MYSQL_PASSWORD: moonkey
      MYSQL_USER: moonuser
    volumes:
      - respawn_mysql_volume:/var/lib/mysql
    ports:
      - "3310:3306"
    networks:
      - respawn_mysql_network

volumes:
  respawn_mysql_volume:

networks:
  respawn_mysql_network:
    driver: bridge
