# For more inforamtion https://www.baeldung.com/spring-boot-yaml-vs-properties
spring:
  application:
    name: 'Respawn Hub'
rawg:
  endpoint: 'https://api.rawg.io/api/games?key='
  apikey: '2fc5fdb2f990452891cbcd397b6037d9'